on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        stack: ["2.3.1"]
        ghc: ["8.10.3"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main' || github.event.ref == 'refs/heads/master'

    - uses: haskell/actions/setup@v1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
        enable-stack: true

    - uses: actions/cache@v2
      name: Cache Stack build
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: |
        stack build --no-nix --ghc-options="-fwrite-ide-info -hiedir=.hie" --force-dirty

    - name: izuna
      uses: matsumonkie/izuna-action@v0.88
      with:
        ghcVersion: '8.10.3'
        hieDirectory: '.hie/'
        projectRoot: '.'
